name: Continuous Integration

on:
  push:
    branches:
      - feat/uji-cicd-baru
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: forumapi_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:coverage
        env:
          HOST_TEST: localhost
          PORT_TEST: 5000
          PGHOST_TEST: localhost
          PGUSER_TEST: postgres
          PGDATABASE_TEST: forumapi_test
          PGPASSWORD_TEST: ${{ secrets.PG_PASSWORD }}
          PGPORT_TEST: 5432
          ACCESS_TOKEN_KEY: 8b7b4ef375716ab08b2a3951b29d52fc00b1c855f9d1a847229b8c5935bef56d9d271e76a9cf08e614300395c3b90ebe559cf968a07411
          REFRESH_TOKEN_KEY: 5078605e074a462b1460608fcbe0d0963c644402e04ad334455ff5a856cb43fd99825861dde02957d5e3184c90c532ca7d0249df20f
